export const GAME_SCENES = {
  PRELOADER_SCENE: 'PRELOADER_SCENE',
  MENU_SCENE: 'MENU_SCENE',
  GAME_SCENE: 'GAME_SCENE',
  SELECT_STAGE_SCENE: 'SELECT_STAGE_SCENE',
  CREDIT_SCENE: 'CREDIT_SCENE',
  STORY_SCENE: 'STORY_SCENE'
}
